### ISSUE TITLE
[Service Windows] Problème avec la reprise

### ISSUE THREAD

**Issue by anisite** [anisite/MESS-Asynchrone.net#1]
Lorsque le service asynchrone lance le traitement via le service web et la méthode "Démarrer" (du serveur applicatif) il semble que celui-ci ne fournisse pas le booléen "Reprise" à "true" dans le fichier XML (DemandeAsynchrone) donc le traitement ne se met pas en reprise.

**Comment by vansfield** [comment]
En test.

**Comment by anisite** [comment]
Pour le moment tu fonctionne!
